[phases.setup]
cmds = ["apt-get update", "apt-get install -y --no-install-recommends libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1 chromium"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "npm start"

[build.args]
NODE_ENV = "production"
